# Generated by Django 5.1.3 on 2025-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vat_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
