# Generated by Django 5.1.3 on 2025-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_vat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vat_id',
            field=models.CharField(max_length=100),
        ),
    ]
