# Generated by Django 5.1.3 on 2025-02-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_name_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
